
services:
  # A Docker web service
  - type: web
    name: Url-Uploader-A
    env: python
    startCommand: python bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/LeoBotsUpdate/url-uploader-A.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: web # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
